In [2]:
import numpy as np

In [4]:
arr = np.arange(0, 11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[5]

5

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [15]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [16]:
arr[:5] = 100

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
rand_arr = np.random.randint(0, 10, 10)

In [20]:
rand_arr

array([2, 7, 7, 2, 6, 9, 4, 9, 2, 3])

In [24]:
bool_arr = rand_arr > 4

In [25]:
bool_arr

array([False,  True,  True, False,  True,  True, False,  True, False,
       False])

In [26]:
rand_arr[bool_arr]

array([7, 7, 6, 9, 9])

In [27]:
rand_arr[rand_arr>4]

array([7, 7, 6, 9, 9])

In [28]:
arr_2d = np.arange(50).reshape(5, 10)

In [29]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])