# NumPy Arrays

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2, 5)) # Build a 2X5 array of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,4)) # build a 3X4 array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,5,100) # build a linear array of length 100 that is evenly spaced from 0 to 5

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [16]:
np.eye(4) # Building an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5) # 5 random numbers across a uniform distribution

array([0.36598743, 0.99468577, 0.78535612, 0.99024338, 0.21997196])

In [18]:
np.random.randn(5) # 5 random numbers across a normal / gaussian distribution

array([ 1.37702739,  0.85850152, -0.71192861, -1.41068596, -1.22721493])

In [19]:
np.random.randn(4,4) # 5 random numbers across a normal / gaussian distribution

array([[ 0.29495164,  0.9834845 , -0.17796836,  1.75318938],
       [ 0.02415016, -1.55712136,  0.11387147,  0.03234023],
       [ 1.08894713, -1.18017906,  1.23754793,  0.15279634],
       [-0.12705479, -0.18752001, -0.86766513,  3.22500622]])

In [21]:
np.random.randint(0, 100, 10) # 10 random integers from 0, 100 

array([93, 16, 64,  0,  3, 20,  1, 83, 71, 65])

In [23]:
arr = np.random.randint(0,100,10)

In [26]:
arr.reshape(2,5)

array([[57, 51, 32, 77, 24],
       [86,  4, 61, 45, 20]])

In [28]:
arr.max()

86

In [29]:
arr.min()

4

In [32]:
arr.argmax()

5

In [34]:
arr.argmin()

6

In [35]:
rearr = arr.reshape(2,5)

In [37]:
rearr

array([[57, 51, 32, 77, 24],
       [86,  4, 61, 45, 20]])

In [38]:
rearr.argmax()

5

In [40]:
arr.shape

(10,)

In [41]:
rearr.shape

(2, 5)